name: Update GVA Data Daily

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create temp directory
      run: mkdir -p temp
        
    - name: Run data update
      run: python gva.py
        
    - name: Set up authentication
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/gva_master.csv
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated data update - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin HEAD:main
        fi
